spring.application.name=ems-backend

spring.datasource.url=${mysql-270b81e7-purusothdon395-9d89.aivencloud.com}
spring.datasource.username=${avnadmin}
spring.datasource.password=${
AVNS_OJoAOfWXlBj4lQICyqW}

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:10602